macro(setupOgre)
    set(OGRE_SOURCE ${OGRE_SOURCE_DIR})
    set(OGRE_BINARIES "${OGRE_SOURCE}/build/gcc/${CMAKE_BUILD_TYPE}" CACHE STRING "Path to OGRE's build folder generated by CMake" )

    IF(NOT EXISTS ${OGRE_BINARIES})
        message(FATAL_ERROR "OGRE_BINARIES:${OGRE_BINARIES} doesn't exists, you need to set it manually") 
    ENDIF()

    set(OGRE_SAMPLE_MEDIA ${OGRE_SOURCE}/Samples/Media)
    if (EXISTS ${OGRE_SOURCE_DIR}/CMake)
        MESSAGE(STATUS "Original FindOGRE.cmake found in OGRE_SOURCE_DIR, trying to use it")
        set(OGRE_TEMPLATE_DIR ${OGRE_SOURCE}/CMake/Templates)
        set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${OGRE_SOURCE_DIR}/CMake  ${OGRE_SOURCE_DIR}/CMake/Packages ${OGRE_SOURCE_DIR}/CMake/Utils)
        FIND_PACKAGE(OGRE REQUIRED)
    else()
        FIND_PACKAGE(OGRE REQUIRED)
    endif()

    FIND_PACKAGE(SDL2 REQUIRED)

    set(OGRE_LIBRARIES ${OGRE_LIBRARIES} ${OGRE_HlmsPbs_LIBRARIES} ${OGRE_HlmsUnlit_LIBRARIES} ${SDL2_LIBRARY} ${OGRE_Overlay_LIBRARIES})
    set(OGRE_SAMPLES_LIBRARIES 
        debug ${OGRE_BINARIES}/lib/libOgreSamplesCommon_d.a
        optimized ${OGRE_BINARIES}/lib/libOgreSamplesCommon.a)
    set(OGRE_SAMPLES_INCLUDE_DIRS ${OGRE_SOURCE}/Samples/2.0/Common/include)

    #config plugins
    if (NOT OGRE_RenderSystem_D3D11_FOUND)
        set(OGRE_COMMENT_RENDERSYSTEM_D3D11 "#")
    endif ()
    if (NOT OGRE_RenderSystem_GL3Plus_FOUND)
        set(OGRE_COMMENT_RENDERSYSTEM_GL3PLUS "#")
    endif ()
    if (NOT OGRE_RenderSystem_GLES_FOUND)
        set(OGRE_COMMENT_RENDERSYSTEM_GLES "#")
    endif ()
    if (NOT OGRE_RenderSystem_GLES2_FOUND)
        set(OGRE_COMMENT_RENDERSYSTEM_GLES2 "#")
    endif ()
    if (NOT OGRE_Plugin_ParticleFX_FOUND)
        set(OGRE_COMMENT_PLUGIN_PARTICLEFX "#")
    endif ()
    set(OGRE_MEDIA_DIR_REL ${CMAKE_SOURCE_DIR}/media)
    set(OGRE_MEDIA_DIR_DBG ${CMAKE_SOURCE_DIR}/media)

    IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
        configure_file( ${CMAKE_SOURCE_DIR}/cmake/Templates/plugins_d.cfg.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/plugins_d.cfg )
        configure_file(${CMAKE_SOURCE_DIR}/cmake/Templates/resources_d.cfg.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/resources_d.cfg @ONLY)
    ELSE() 
        configure_file( ${CMAKE_SOURCE_DIR}/cmake/Templates/plugins.cfg.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/plugins.cfg )
        configure_file(${CMAKE_SOURCE_DIR}/cmake/Templates/resources.cfg.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/resources.cfg @ONLY)
    ENDIF()
    configure_file(${CMAKE_SOURCE_DIR}/cmake/Templates/resources2.cfg.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/resources2.cfg @ONLY)

    include_directories(
        ${OGRE_Plugin_ParticleFX_INCLUDE_DIRS}
        ${OGRE_RenderSystem_GL3Plus_INCLUDE_DIRS}
        ${OGRE_RenderSystem_Direct3D9_INCLUDE_DIRS}
        ${OGRE_RenderSystem_Direct3D11_INCLUDE_DIRS}
        ${OGRE_RenderSystem_GL3Plus_INCLUDE_DIRS}
        ${OGRE_Overlay_INCLUDE_DIRS}
        ${OGRE_HlmsPbs_INCLUDE_DIRS}
        ${OGRE_HlmsUnlit_INCLUDE_DIRS}
        ${SDL2_INCLUDE_DIR}
        )
endmacro()
